### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Thomas2love** [Ecodev/newsletter#126]
Is there a way to control the mail qeue batch size. To prevent flooding and protect your reputation? You could tell a bit more about this.

In general I get the idea that the documentation does not tell everything possible. (comparison direct_mail?) At first sight direct_mail seems more attractive because they tell me the things I am looking for. This is a pity since you spend so much time actively developing this extension

**Comment by PowerKiKi** [comment]
We try to provide reasonable default value, but you can customize it via the `mails_per_round` value in Extension Manager. I believe it is [documented here](https://docs.typo3.org/typo3cms/extensions/newsletter/Configuration/Index.html?highlight=mails_per_round#constants), although I see why you would not have found it...

I know the documentation is a bit lacking, but contributions really are more than welcome. Please add the missing info how/where you would like to have found them in the docs. I'll merge it.

**Comment by PowerKiKi** [comment]
Oh, there is a [comparison with TC DirectMail](https://docs.typo3.org/typo3cms/extensions/newsletter/Introduction/Index.html#how-it-compares), but not DirectMail, especially not the recents versions.

TC DirectMail was a fork of DirectMail because back then it was kinda dead/obsolete. Then I forked TC DirectMail because it also became obsolete. Newsletter now still share the same concepts with TC DirectMail (and so I guess also DirectMail), but it's been entirely rewritten with extbase brand new coding style. But as far features goes, I honestly couldn't how Newsletter compare to today's DirectMail... Again if you are interested to make a feature table comparaison, be my guest. You can do that on this project wiki/doc, or anywhere else where you see it fit.
