### ISSUE TITLE
Can't edit Recipient List in BE

### ISSUE THREAD

**Issue by steffenk** [Ecodev/newsletter#136]
If i create a Recipient List in BE inside sysfolder, all is ok. But if i try to edit one, i get empty page. No error log, just nothing.
all other record types are working.

php 7.1, TYPO3 7.6.14, newsletter master

**Comment by PowerKiKi** [comment]
what about inside a non-sysfolder page ? is the same behavior ?

also when do you get empty page, after clicking "save" ? or you cannot even see it at all ?

**Comment by steffenk** [comment]
testet on other instance with TYPO3 8.6.1, there it works. So there must be something special in this installation. Any hints where to search?

**Comment by steffenk** [comment]
after save i see the record in list, all looks fine. Error occurs after i click on edit record.

**Comment by PowerKiKi** [comment]
not much... try to enable as much logging as possible, including xdebug, and dig in...

> what about inside a non-sysfolder page ? is the same behavior ?

**Comment by steffenk** [comment]
it's already full dev stack :)

Now i get this error:
Illegal string offset 'config' in typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php

seems some problems with config here, i also tried to insert the ts again in ext template of the sysfolder. btw - same problems on regular pages.

**Comment by steffenk** [comment]
Problem solved! It was the extension "UrlTool" which was used for 404 handling, and for whatever reasons it invoked the BE edit process.

**Comment by PowerKiKi** [comment]
I also stumbled on the same issue a few days ago. It still is that frontend URI building from the backend issue and it is really annoying. I can't understand why TYPO3 does not have a proper way to handle that.

Anyway, the important fact is that it is now fixed in latest 3.2.0 version (by bypassing entirely the official UriBuilder) and you should not experience the issue anymore, even with UrlTool... or so I hope...
