### ISSUE TITLE
Problem with redirects

### ISSUE THREAD

**Issue by r4fx** [Ecodev/newsletter#138]
Hi,
I have a problem with redirecting clicked links to their targets,
every link (opening from email) opens web version of newsletter instead of real target page,
parameters are trensfered with link, but there is no redirection.

Example link:

`http://foo.com/newsletter/?tx_newsletter_p%5Bn%5D=23&tx_newsletter_p%5Bl%5D=31bd425fe2ab19b129ae16400e7b1b7a&tx_newsletter_p%5Baction%5D=clicked&tx_newsletter_p%5Bcontroller%5D=Link`

I would be glad for any help.

My environemnts:
TYPO3 7.6.18
PHP 7.0.19
Domain record set on the root of page.

**Comment by PowerKiKi** [comment]
A proper link with spy enabled [should include](https://github.com/Ecodev/newsletter/blob/master/Tests/Functional/Fixtures/mailer/output-2-true-true.eml#L28-L30) the `type` parameter. So it would look like in the email source:

`http://example.com/index.php?id=2&type=1342671779&tx_newsletter_p%5Bn%5D=12345&tx_newsletter_p%5Bl%5D=b2ca893c8e2ddb5cf431dfcf66f3cc48&tx_newsletter_p%5Baction%5D=clicked&tx_newsletter_p%5Bcontroller%5D=Link`

The one you gave is does not include that `type` parameter, so you should focus on that. Why is the parameter missing ? Because the link is generated by TYPO3 URI Builder, my bet is it has something to do with RealURL (or equivalent). Try disabling it...

**Comment by r4fx** [comment]
Thank you for the answer, I managed to get redirection works,
that's what I did:

- turn-of cooluri
- set absRefPrefix with domain

in reference to the above I have 2 questions:
- do I need to use `config.absRefPrefix = foo.com` instead of `absRefPrefix = /` to handle redirects correctly ?
- Is there any way to keep pretty links generated with cooluri ?

**Comment by PowerKiKi** [comment]
I don't know cooluri at all, so I'm afraid I won't be able to help you about that. If you do find out how, it would be nice to post back here, or create a PR for [the docs](https://docs.typo3.org/typo3cms/extensions/newsletter/Configuration/Index.html#configuration-realurl)
