### ISSUE TITLE
Remove "show in browser" when in browser

### ISSUE THREAD

**Issue by dscoding** [Ecodev/newsletter#19]
The link to the browser view is also shown when in browser. The link should be removed there.

**Comment by marvin-martian** [comment]
The proplem with the above method is that the email content is already rendered when you click the view url in the mail. I would do this a different way... 
 
In the Email model I would add a extra var denoting that it was a 'webview'
```php

Ecodev\Newsletter\Domain\Model\Email->getViewUrl
......
    public function getViewUrl()
    {
        return UriBuilder::buildFrontendUri($this->getPid(), 'Email', 'show', ['c' => $this->getAuthCode(),'w' => 'webview']);
    }
......
```

Then in the EmailController showAction just before you set the content to display it, call a 'webview' hook to allow a custom method to modify the raw content if the user so pleases.

```php
Ecodev\Newsletter\Controller\EmailController->showAction
......
        if (isset($args['w'])) {
            // Webview Hook here
            if (is_array($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['newsletter']['webviewHook'])) {
                foreach ($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['newsletter']['webviewHook'] as $_classRef) {
                    $_procObj = GeneralUtility::getUserObj($_classRef);
                    $content= $_procObj->webviewHook($content);
                }
            }
        }

        $this->view->assign('content', $content);
    }
......
```
That way you don't have to worry about how someone wants to particularily display their webview of the mail, they can modify the entire view themselves anyway they like.

**Comment by marvin-martian** [comment]
...or may just add a general viewHook anyway at this point?

**Comment by PowerKiKi** [comment]
> the email content is already rendered when you click the view url in the mail

If I understood correctly what you mean, this is not true. Once you click the link in the email and your browser open the newsletter, the content is re-generated (almost) from scratch. That means that if the newsletter content changed between the sending and the viewing in the browser it will reflect those changes.

This is a feature, to allow to fix typos easily, which also happens to make the whole system lighter on the DB (don't need to store Mb of almost duplicated content that will almost never be used). But it also means that the marker approach I suggested is technically possible. And it also cleaner, easier to use, and easier to maintain than a hook IMHO. So it still has my preference if somebody want to submit a PR for that.

**Comment by marvin-martian** [comment]
In the end I did implement the webviewHook for myself setting the 'w' requestVar. Because then you know for sure you are in a browser view. ala: https://github.com/Ecodev/newsletter/issues/19#issuecomment-285854729

From the hook I just stripped out the bits I didnt want in browser view by parsing the DOM of the mail content. Works perfectly.

[offtopic]
BTW I had a small discussion with Dmitry from RealURL, he is not so happy that everyone keeps trying to generate RealURL paths via the BE, only because RealURL is configured from a TYPO3_MODE FE perspective. He tried to enforce his 'FE Only' stance recently and it broke the RealURL support in the 'newsletter' extension. It also broke many other extensions including 'solr'. He has since reversed his enforcement because it was creating havoc.

Though he is right, generating RealURL paths via the BE could be unpredictable depending on the RealURL configuration. 

In the newsletter you render the newsletter html-mail by instantiating a TSFE object in the BE, but the TYPO3_MODE is still BE because it is immutable. To be safe you would need to render the html-mail in a true FE TYPO3_MODE. You could probably grab a 'hidden' render by using cURL/file_get_contents.

Though at some point I think RealURL needs to be binned and a new path routing system created in the the core of Typo3 which is less BE/FE context dependent.

**Comment by marvin-martian** [comment]
Thinking about it, doesnt that mean we are in a browser view when TYPO3_MODE = 'FE'? That might be an easier way to check whether or not to remove "show in browser". lol ;-)

**Comment by PowerKiKi** [comment]
Actually `TYPO3_MODE` is always 'FE' when rendering the newsletter content. This is because Newsletter itself use cURL to fetch the content as any other normal user would.

So there really is only one single difference between rendered for the browser and rendered to be sent. And that is the `User-Agent` header used by Newsletter when retrieving content to be sent. Read more about that in af7e6452331f6eeac843d156e65cb271c8591406.

When it comes to URI building and RealUrl usage, I really wished there was a simple way to to solve that very basic need. I am dumbfounded that it is, AFAIK, still not available in TYPO3. I have been fighting with that extremely dirty hack for months now, and I am far from pleased by the situation. By all means we need a proper official way to solve that. Is there any "official" discussion about that that you could point me to ?

**Comment by marvin-martian** [comment]
The TYPO3_MODE FE issue is in UriBuilder. You simulate the the frontend to build URLs, when the mode is BE. This effected RealURL, when Dmitry enforced "FE only" it broke the extension by throwing an exception. As for the discussion on a routing method in the core I don't know. But it makes sense most other frameworks out there do this.

**Comment by marvin-martian** [comment]
To tell you the truth I feel this TYPO3_MODE historical paradigm needs to go. The assumption needs to be you are always in FE context and you should never have to check this context to configure anything for the FE. It is only when you are performing BE operations do you need to check for a BE_MODE definition. That would go along way to avoid BE hacks and provide a powerful flexibility. Of course throwing out TYPO3_MODE will break backwards compatibility, but so many breakages have been made between 4-8 it is better it is done sooner than later.

**Comment by PowerKiKi** [comment]
IMHO the entire concept of frontend and backend should disappear. I don't see any technical reason for that difference to exists. But that's way out of topic ;-)

**Comment by PowerKiKi** [comment]
Closing because this is not likely to happen in the foreseeable future (too much effort for very little gain).
