### ISSUE TITLE
hard and softbounces as array to external file?

### ISSUE THREAD

**Issue by githubrsys** [Ecodev/newsletter#54]
Wold make sense due the possibility of location specific mailserver messages.

**Comment by PowerKiKi** [comment]
I would rather complete the existing list of regexp used to detect soft/hard bounces, so it benefit the entire community. If you have something to contribute on that topic, feel free to submit a PR (probably for ``Classes/BounceHandler.php``)

As for exporting a list of bounces, I would strongly suggest to use a [SQL RecipientList](https://github.com/Ecodev/newsletter/blob/master/Documentation/SQL%20examples%20for%20Recipient%20List.rst). That way you have the opportunity to create records however it fits your environnement. Or if you think it is worth it, you can implement your own ``RecipientList`` and use that instead of the built-in ones.
