### ISSUE TITLE
does errors while sending the newsletter get catched?

### ISSUE THREAD

**Issue by MoppieMop** [Ecodev/newsletter#63]
I had the problem that my hoster blocked some mails. But the newsletter-module does not report any error.
I cant see any error-catching during send() the mails. Is there a functionality? If not - isn't this a good idea?

**Comment by PowerKiKi** [comment]
Since newsletters are sent via Scheduler,  there is no exception catching
mechanism implemented in Newsletter. But Scheduler does catch exceptions
and report them in BE.

If anything should be done I guess it should be done in Scheduler. To be
able to see all previous exceptions (not only the last one) would indeed be
useful.

If you are talking about error/warnings, then those should be printed to
CLI when executing Scheduler. If you are using CRON then you can get an
email containing that output. That gives you an error/warning notification
service.

Alternatively you can configure PHP to log errors/warnings somehwhere else
(syslog, etc).

**Comment by PowerKiKi** [comment]
Closing because of lack of feedback. Please re-open with new information if need be.

**Comment by MoppieMop** [comment]
Now years later I am again with tx_newsletter. I know it is not the same problem, but it is again about error-reporting: I tried to setup the newsletters with a test-reciepient-list (CSV):
```
name, email 
moppie, moppie@test.de
```
When i hit "send test emails" i got a message "newsletter has been sent". But there was no newsletter. emailCount was 0 too. 
At last I found out the problem was the space before the email. But it would be really helpful if there where some kind of error-reporting in the popup and not the misleading success-message.

**Comment by PowerKiKi** [comment]
Indeed invalid emails are ignored silently:

https://github.com/Ecodev/newsletter/blob/a5d2ae2245a753b78b5889acc0f75c8418336b5b/Classes/Tools.php#L130

Please open a new issue with suggestion on how to implement a solution, or better yet create a PR for it. As for now, we don't have an obvious way on how to report error on a email basis. I guess just logging it in TYPO3 log might already be a cheap improvement...
