### ISSUE TITLE
allow for SSL connections on bounce accounts

### ISSUE THREAD

**Issue by marvin-martian** [Ecodev/newsletter#68]
It would be nice if imaps on port 993 and pop3s on port 995 was supported for bounce accounts. This would require a port column in tx_newsletter_domain_model_bounceaccount and a modification in the fetchrc to support ssl ports.

**Comment by PowerKiKi** [comment]
It makes a lot of sense. If you are willing to create a PR for that, I would merge it.

We also had a discussion via email with Morten Kjems who wanted SSL support to be able to support gmail. No work was really done, but if the need arise, then we could consider storing the whole fetchmail file instead of individual info (server, username, etc), so Newsletter would just "forward" your configuration to fetchmail. That would give you, and any other user, total control on fetchmail.

**Comment by PowerKiKi** [comment]
Fixed by 671ca4e47377026ee4135ba8c1faf3f16ed170e1 and released in 2.6.0
