### ISSUE TITLE
map link paramenters in newsletter to a single hash/url shortener

### ISSUE THREAD

**Issue by marvin-martian** [Ecodev/newsletter#69]
If the link parameters &url=http://.........&n=&l= etc... on newsletter links were all bundled into a single hash it would possibly shorten link urls and reduce any risk of link manipulation.

For example:
```
http://?tx_newsletter_p%5Baction%5D=clicked&tx_newsletter_p%5Bcontroller%5D=Link&tx_newsletter_p%5Bidentifier%5D=asfasasdfasdf
```

Or even just :
```
http://.../?tx_newsletter_p%5Bidentifier%5D=asfasasdfasdf
```
Where the action and controller are also included in the shortener.

**Comment by PowerKiKi** [comment]
What would be the issue of "link manipulation" that would not be anyway possible with the entire URL ? IMHO the `url` parameter does not need to be more secure than the entire URL itself.

Also the shortening of the URL is not possible, because Newsletter must be able to redirect to the final URL even if the database was truncated (meaning we don't break very old emails).

As for "hiding" controller/action parameters it should, theoretically, be possible to configure RealURL to build whatever links you would like. If you happen to do that, I would appreciate that you let me know how you did, so I can add in the documentation.

**Comment by marvin-martian** [comment]
> What would be the issue of "link manipulation" that would not be anyway possible with the entire URL ?

By link manipulation I mean a third-party being able to modify the url parameter. For example it would be very easy to  redirect to another, possibly malicious, website by modifying this parameter. If the url was hashed it would be impossible to do this. So if the entire URI looks like it goes back to the original site but has a malicious URL in the url parameter it may confuse an unexpecting user. This is at the lowest level a security issue considering that no checks are made on the url parameter if it is an URL that is expected. By hashing the URL and then looking up that hash in DB it would make it more secure, because you then know that it is the redirect that is intended, and not a possibly manipulated value. If the hash is tampered you will not get a match and you can redirect to a 404.

``` PHP
 /**
     * Register when a link was clicked and redirect to link's URL.
     * For this method we don't use extbase parameters system to have an URL as short as possible
     */
    public function clickedAction()
    {
        $this->linkRepository->registerClick(@$_REQUEST['n'], @$_REQUEST['l'], @$_REQUEST['p']);

        // Finally redirect to the destination URL
        $url = @$_REQUEST['url'];
        header("Location: $url");
        die();
    }
```

> Also the shortening of the URL is not possible, because Newsletter must be able to redirect to the final URL even if the database was truncated (meaning we don't break very old emails).

If the database is truncated you have bigger issues than breaking very old mails. Typo3 is database driven. URL shortening IS possible it just needs to be implemented. But if you are concerned about this write the hash pairs in a text file.

> As for "hiding" controller/action parameters it should, theoretically, be possible to configure RealURL to build whatever links you would like

I dont mean to hide the controller/action paramenters but if you are hashing the parameters you could theoretically include them as well. It should not create a problem.

**Comment by marvin-martian** [comment]
```PHP
$url = @$_REQUEST['url'];
header("Location: $url");
die();
```

This type of coding is dangerous because it can be seriously abused... it can make you a proxy in a denial of service attack.

**Comment by PowerKiKi** [comment]
You are right for URL open redirection, as explained in details by [OWASP](https://www.owasp.org/index.php/Top_10_2010-A10-Unvalidated_Redirects_and_Forwards). This must be fixed.

As for truncating tables, I meant that Newsletter is built to be able to keep working even if some tables are truncated (namely `tx_newsletter_domain_model_linkopened` and `tx_newsletter_domain_model_email`). Obviously if the entire database is truncated it won't work that well :stuck_out_tongue_closed_eyes:. But this actually has nothing to do with URL redirecting, so it was not a very strong argument from my part.

Finally, I don't think I can touch anything for controller/action parameters, otherwise TYPO3 would not route the request to the extension. For those, I believe the best way to go is via RealURL or similar extension.

**Comment by marvin-martian** [comment]
> Finally, I don't think I can touch anything for controller/action parameters, 
You dont have to worry about this if you set the hash to the controller, then Typo3 will route it to the extension. Once you have the hash, you do a look-up, unserialize the stored parameters and process as ususal. RealURL is not necessary.

**Comment by PowerKiKi** [comment]
> set the hash to the controller

I may need more explanation about that. How would TYPO3 know that it is a request for Newsletter and route to Newsletter (to then allow me to do whatever is necessary with my hash), if TYPO3 cannot find the controller/action in the first place ? Any doc/example ?

**Comment by marvin-martian** [comment]
I need this working and this security hole closed ASAP, so I will try and bring you something.

**Comment by marvin-martian** [comment]
I have a little time for the next 2-3 days to hammer this out with you if you want....

**Comment by marvin-martian** [comment]
Just a quick look it seems you can override the method initializeAction()  in the Extbase ActionController. This gets called before the action method is called. It is also possible to override resolveActionMethodName() in the same class. Maybe that is better as it happens earlier.  You create the override in Ecodev\Newsletter\MVC\Controller\ExtDirectActionController.

**Comment by PowerKiKi** [comment]
AFAIK this does not solve the issue of TYPO3 not knowing that he should call anything in Newsletter. If TYPO3 does not know the request is for Newsletter, then there is no way for Newsletter to do anything in the first place... or am I missing obvious ?

**Comment by marvin-martian** [comment]
Oh you are right you still need a action/controller. What  was I thinking..  O_o
i.e. ?tx_newsletter_p[controller]=controller_name&tx_newsletter_p[action]=sha1_hash

The 'sha1_hash' action method does not exist... it is a hash. So when you try to resolve the controller method name that is when you need to resolve the hash in  a lookup for the parameters.

I guess the only way to hash the controller and action as well would be to configure the newsletter plugin to bootstrap the extbase extension. 

Then you could do something like (to just have a single param): 
?tx_newsletter_p[process]=sha1_hash

**Comment by PowerKiKi** [comment]
I think we now agree. But I feel a bit over-complicated to to "manually" route requests to Newsletter if we can rely on a specialized extension instead (eg: RealUrl). With proper configuration I guess we could have a link similar to:
`/newsletter_click?n=1757&l=10acbf98c3d5d3337db73bd23e78ccf4`

which sound good enough to me, especially because it does not require any modification in Newsletter and give you the freedom to customize the link. I'll try to see if I can come up with a RealURL configuration example for that...
