### ISSUE TITLE
Respect PID for objects

### ISSUE THREAD

**Issue by siwa-pparzer** [Ecodev/newsletter#93]
When you have multiple Sites in one Typo3 System every editor sees every recipient list.
Every editor should only see the recipient lists of his current Website.

Should be very easy:
RecipientListController.php:
Line 60 listAction:

        $recId = $this->settings["recipientPid"];
    	if($recId){
			$recipientLists = $this->recipientListRepository->findByPid($recId);			
		}else{
			$recipientLists = $this->recipientListRepository->findAll();
		}

Setup:
module.tx_newsletter.settings.recipientPid =

**Comment by PowerKiKi** [comment]
The current behavior is on purpose (see `AbstractRepository::createQuery()`. This is because we never had the need for a specific PID in our projects and it seemed more a hindrance than a feature.

However I understand your use-case and it makes senses. I would be willing to accept a PR to support that case, as long as it follows those requirements:

* don't break behavior for existing  install
* be generic enough to work with all object types
* be as standard as possible. I think i saw a standard way to define PIDs, maybe extension builder could provide an example for best practices
* unit/functional tests covered

My first guess is that modyfing the method mentioned earlier to conditionnaly call `setRespectStoragePage()`would be enough, but that need to be tested.

**Comment by siwa-pparzer** [comment]
I wouldn't support every object type because for example the object types 'Newsletter' and 'Email' are stored on the specific site, where the newsletter was created/sent.
So, the user has no access to other objects, than his own ones.
The only object type that is excluded from this behaviour is the RecipientList because it is stored statically on one page.
I think "setRespectStoragePage()" isn't needed because "->findByPid()" does the work here.

So i would add the mentioned condition in the listAction (I think it isn't needed elsewhere) and add the Setting Variable in the constant.txt and setup.txt.
The default value would be empty, so the current behavior doesn't change, but if a admin wants to restrict RecipientLists for his users, he can add a PID and the condition triggers.

I think implementing a storageRestriction for the whole plugin isn't really needed.
I tested the changes on a current Typo3 Installation and it works perfectly.

Best Regards
Philipp

**Comment by PowerKiKi** [comment]
* Newsletter
* RecipientList
* BounceAccount
* Email
* Link

Of all those types, only `Newsletter` cannot be on a different PID (it would break content fetching). `RecipientList` and `BounceAccount` both have equally reasonable use-cases to have a configurable PID. As for `Email` and `Link` while it would not break anything I can't see why somebody would want to store them somewhere else. But still, for consistency sake, I believe it _should_ be allowed to.

So at the very least `RecipientList` and `BounceAccount` must be implemented. Because they really should follow the same logic.

Also I believe `module.tx_newsletter.persistence.storagePid` would be the standard way to define that. But I guess we can find some compromise if we want different PID for different object types...

**Comment by siwa-pparzer** [comment]
Ok, further steps:
* I'll add a Constant `module.tx_newsletter.persistence.storagePid`
* I'll set `setRespectStoragePage()` for `RecipientList` and `BounceAccount` (or any other changes that will be needed)
* I'll test the changes

Wish me luck

**Comment by PowerKiKi** [comment]
To submit a PR it's always best to create a branch yes. The name doesn't really matter and you can branch out from master or develop because most of the time they are very similar.

You can create a PR and push as many commits as you see fit for dicussion purpose. When it's ready to get merged we may squash commits into one. Depending how messy it gets... but i guess it should not be too complicated... hopefully...

**Comment by siwa-pparzer** [comment]
Made the changes, but when I want to make a pull request it says "Authentication Failed (You may not have permission to access newsletter. Check Preferences to make sure you’re still logged in.)"

**Comment by PowerKiKi** [comment]
It seems you are using GitHub Desktop. I can't help you with that. If you use the web interface, you should fork Newsletter, then push your commit on your fork and finally create a PR (there should be a button somewhere on the page) from your fork to this project.

**Comment by siwa-pparzer** [comment]
started a Pull-request

**Comment by githubrsys** [comment]
Seems as if this can be closed with 499403d768ccd3b2796b7f47a53adbda3fec3453 , right?

**Comment by siwa-pparzer** [comment]
yes
