### ISSUE TITLE
limit the logs

### ISSUE THREAD

**Issue by MoppieMop** [Ecodev/newsletter#95]
My scheduler has a job to send every 2 minutes newsletter. Obviously there are not all the time newsletters to send. But my log got spamed with `[newsletter] Sent 0 emails`.
Maybe it is better to log only if mails are actually send. Another solution would be to disable some kind of newsletter-logging through extension-configuration.

**Comment by PowerKiKi** [comment]
> every 2 minutes newsletter

That seems unreasonably too often. I'd say something like every 30 minutes or so should be enough for most use-cases. Why would you run that job so often ?

Also since 2.6.0 we use the new logging API, that means you can [configure it](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Logging/Configuration/Index.html#logging-configuration) however you like to discard all logs or filter them via a custom writer, or send them to somewhere where the clutter would not bother you.

I believe `Sent 0 emails.` is an important information that should be kept for (high level) debugging purposes.
